name = "ezpath-router"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "8006c17f0bd3f3b0e8b7979097fc87ed"

[vars]
CDP_FACILITATOR_URL = "https://x402.org/facilitator"
SUPABASE_URL = "https://dikmzrgwpjbdnrauffzs.supabase.co"

[[kv_namespaces]]
binding = "METERING"
id = "2fdd6978310a44a18ff0e34da538c9a0"

[[routes]]
pattern = "ezpath.myezverse.xyz"
custom_domain = true
