/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known.agent[.]json'
import { Route as ApiV1QuoteRouteImport } from './routes/api/v1/quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1QuoteRoute = ApiV1QuoteRouteImport.update({
  id: '/api/v1/quote',
  path: '/api/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/v1/quote': typeof ApiV1QuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/v1/quote': typeof ApiV1QuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/v1/quote': typeof ApiV1QuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/.well-known/agent.json' | '/api/mcp' | '/api/v1/quote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/.well-known/agent.json' | '/api/mcp' | '/api/v1/quote'
  id:
    | '__root__'
    | '/'
    | '/.well-known/agent.json'
    | '/api/mcp'
    | '/api/v1/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiV1QuoteRoute: typeof ApiV1QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/quote': {
      id: '/api/v1/quote'
      path: '/api/v1/quote'
      fullPath: '/api/v1/quote'
      preLoaderRoute: typeof ApiV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiV1QuoteRoute: ApiV1QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
